# Generated by Django 4.0.10 on 2024-06-02 09:40

from django.db import migrations, models
import tinymce.models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(unique=True)),
                ('background_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='images/hompage-carousel/')),
                ('heading', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=300)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(default='Read More', max_length=64)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home'), ('ABOUT', 'About'), ('CONTACT', 'Contact'), ('TEST', 'Test')], max_length=8, unique=True)),
                ('heading', models.CharField(default='Content Page', max_length=64)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
