# Generated by Django 4.0.10 on 2024-06-02 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import portfolio.models
import tinymce.models


class Migration(migrations.Migration):


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(unique=True)),
                ('summary', models.TextField(max_length=300, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=32)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, default='images/default-project.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[512, 512], upload_to=portfolio.models.file_path)),
                ('summary', models.TextField(default='Default project summary', max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('technology', models.CharField(max_length=32)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('jenkins_url', models.URLField(blank=True, max_length=500)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.category')),
                ('visible', models.BooleanField(default=False)),
                ('demo_url', models.URLField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='images/projects/gallery_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=32)),
                ('credited_for', models.CharField(max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
